version: '3.4'

services:
  k8sdemoapi:
    image: k8sdemoapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_k8sdemoapi$
    volumes:
      - D:\projects\git\K8SDemo\K8SDemoAPI:/app
      - C:\Users\kevin6535.lin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_k8sdemoapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_k8sdemoapi$ bin/Debug/netcoreapp2.0/K8SDemoAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

  k8sdemowebv1:
    image: k8sdemowebv1:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_k8sdemowebv1$
    volumes:
      - D:\projects\git\K8SDemo\K8SDemoWebV1:/app
      - C:\Users\kevin6535.lin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_k8sdemowebv1$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_k8sdemowebv1$ bin/Debug/netcoreapp2.0/K8SDemoWebV1.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""


  k8sdemowebv101:
    image: k8sdemowebv101:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_k8sdemowebv101$
    volumes:
      - D:\projects\git\K8SDemo\K8SDemoWebV101:/app
      - C:\Users\kevin6535.lin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_k8sdemowebv101$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_k8sdemowebv101$ bin/Debug/netcoreapp2.0/K8SDemoWebV101.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

